CREATE TABLE `dataplex-metadata.MEDITECH.MRIPatientContact`
(
  address_line1 STRING,
  address_line2 STRING,
  contact STRING,
  contact_type_id INT64,
  data_source_id INT64,
  email STRING,
  fax STRING,
  first_name STRING,
  home_phone STRING,
  language_id INT64,
  last_name STRING,
  medicare_card_number STRING,
  middle_name STRING,
  mri_patient_contact_id INT64,
  mri_patient_id INT64,
  mt_updated TIMESTAMP,
  name STRING,
  orders INT64,
  other_phone STRING,
  relationship_id INT64,
  source_code STRING,
  suburb_id INT64,
  title_id INT64,
  updated_utc TIMESTAMP,
  work_phone STRING,
  PRIMARY KEY (mri_patient_id) NOT ENFORCED,
  CONSTRAINT MRIPatientContact_fk FOREIGN KEY (mri_patient_id) REFERENCES `dataplex-metadata.MEDITECH.MRIPatient`(mri_patient_id) NOT ENFORCED
);
