CREATE TABLE `dataplex-metadata.MEDITECH.Patient`
(
  address_line1 STRING OPTIONS(description="First line of the patients address"),
  address_line2 STRING OPTIONS(description="Second line of the patients address"),
  confirmed BOOL OPTIONS(description="Indicates whether the patient information has been confirmed"),
  data_source_id INT64 OPTIONS(description="ID of the data source from which the patient information was obtained"),
  dob DATE OPTIONS(description="Date of birth of the patient"),
  dva_card_number STRING OPTIONS(description="DVA card number of the patient"),
  dva_card_type_id INT64 OPTIONS(description="ID of the DVA card type"),
  email STRING OPTIONS(description="Email address of the patient"),
  employment_status_id INT64 OPTIONS(description="ID of the patients employment status"),
  ethnicity_id INT64 OPTIONS(description="ID of the patients ethnicity"),
  fax STRING OPTIONS(description="Fax number of the patient"),
  first_name STRING OPTIONS(description="First name of the patient"),
  force_id STRING OPTIONS(description="Force ID of the patient"),
  gender_id INT64 OPTIONS(description="ID of the patients gender"),
  home_language_id INT64 OPTIONS(description="ID of the patients home language"),
  home_phone STRING OPTIONS(description="Home phone number of the patient"),
  indigenous_status_id INT64 OPTIONS(description="ID of the patients indigenous status"),
  interpreter_required BOOL OPTIONS(description="Indicates whether the patient requires an interpreter"),
  last_name STRING OPTIONS(description="Last name of the patient"),
  marital_status_id INT64 OPTIONS(description="ID of the patients marital status"),
  medicare_card STRING OPTIONS(description="Medicare card number of the patient"),
  medicare_card_expiry DATE OPTIONS(description="Expiry date of the patients Medicare card"),
  medicare_card_ref_num STRING OPTIONS(description="Medicare card reference number of the patient"),
  middle_name STRING OPTIONS(description="Middle name of the patient"),
  mothers_first_name STRING OPTIONS(description="First name of the patients mother"),
  name STRING OPTIONS(description="Full name of the patient"),
  other_name STRING OPTIONS(description="Other name of the patient"),
  other_phone STRING OPTIONS(description="Other phone number of the patient"),
  patient_code STRING OPTIONS(description="Patient code assigned to the patient"),
  patient_id INT64 OPTIONS(description="Unique identifier for the patient"),
  pension_hcc_number STRING OPTIONS(description="Pension HCC number of the patient"),
  pension_status_id INT64 OPTIONS(description="ID of the patients pension status"),
  pharmacy_benefit_number STRING OPTIONS(description="Pharmacy benefit number of the patient"),
  preferred_name STRING OPTIONS(description="Preferred name of the patient"),
  race_id INT64 OPTIONS(description="ID of the patients race"),
  religion_id INT64 OPTIONS(description="ID of the patients religion"),
  residential_status_id INT64 OPTIONS(description="ID of the patients residential status"),
  safety_net_number STRING OPTIONS(description="Safety net number of the patient"),
  sex STRING OPTIONS(description="Sex of the patient"),
  south_sea_islander_id INT64 OPTIONS(description="ID of the patients South Sea Islander status"),
  suburb_id INT64 OPTIONS(description="ID of the patients suburb"),
  title_id INT64 OPTIONS(description="ID of the patients title"),
  updated_utc TIMESTAMP OPTIONS(description="Timestamp indicating when the patient information was last updated"),
  wa_health_urn STRING OPTIONS(description="WA Health URN of the patient"),
  war_widow BOOL,
  work_phone STRING,
  PRIMARY KEY (patient_id) NOT ENFORCED,
  CONSTRAINT Patient_fk FOREIGN KEY (patient_id) REFERENCES `dataplex-metadata.MEDITECH.MRIPatient`(mri_patient_id) NOT ENFORCED
);
